### ISSUE TITLE
Mismatched code snippet and output image in documentation?

### ISSUE THREAD

**Issue by SwaroopSomanna** [ghost1372/ghost1372#1]
The screeshot attached below is the webpage explaining `UniformSpacingPanel`. The code snippet doesn't produce the attached output. Please see.   
![Screenshot_20210218-204239.png](https://user-images.githubusercontent.com/32904377/108377783-62665a80-722a-11eb-9f07-7f1ee84f6f35.png)

**Comment by ghost1372** [comment]
@SwaroopSomanna  this is my profile repo 😅
if you have any issues with docs please mention in docs repo https://github.com/ghost1372/ghost1372.github.io
also i fixed this mismatched (refresh page and see codes)
https://hosseini.ninja/handycontrol/extend_controls/uniformSpacingPanel/
